repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.13.3
    hooks:
    # run the linter
    - id: ruff
      args: [ --fix ]
    # run the formatter
    - id: ruff-format
        